import pygame

WIDTH = 630
HEIGHT = 630
YLIN_KUULA_X = WIDTH // 2 -1
YLIN_KUULA_Y = 48
ALIN_KUULA_X = WIDTH // 2 -1
ALIN_KUULA_Y = HEIGHT - 63
VALI = 32
P_KOKO = 13

lauta = pygame.image.load('chinese_lauta.png')
naytto = pygame.display.set_mode((WIDTH, HEIGHT))
kello = pygame.time.Clock()

vihrea = (0, 170, 96) 
ruskea = (120, 80, 33) 

koordinaatit1 =  [(YLIN_KUULA_X, YLIN_KUULA_Y), 
 (YLIN_KUULA_X - 19, YLIN_KUULA_Y + VALI), (YLIN_KUULA_X + 19, YLIN_KUULA_Y + VALI),  
 (YLIN_KUULA_X - 38, YLIN_KUULA_Y + 2*VALI), (YLIN_KUULA_X, YLIN_KUULA_Y + 2*VALI), (YLIN_KUULA_X + 38, YLIN_KUULA_Y + 2*VALI),
 (YLIN_KUULA_X - 19-38, YLIN_KUULA_Y + 3*VALI),  (YLIN_KUULA_X - 19, YLIN_KUULA_Y + 3*VALI), (YLIN_KUULA_X + 19, YLIN_KUULA_Y + 3*VALI), (YLIN_KUULA_X + 19+38, YLIN_KUULA_Y + 3*VALI)  
]  


koordinaatit2 =  [(ALIN_KUULA_X, ALIN_KUULA_Y),
(ALIN_KUULA_X - 19, ALIN_KUULA_Y - VALI), (ALIN_KUULA_X + 19, ALIN_KUULA_Y - VALI),
(ALIN_KUULA_X - 38, ALIN_KUULA_Y - 2*VALI), (ALIN_KUULA_X, ALIN_KUULA_Y - 2*VALI), (ALIN_KUULA_X + 38, ALIN_KUULA_Y - 2*VALI),
(ALIN_KUULA_X - 19-38, ALIN_KUULA_Y - 3*VALI),  (ALIN_KUULA_X - 19, ALIN_KUULA_Y - 3*VALI), (ALIN_KUULA_X + 19, ALIN_KUULA_Y - 3*VALI), (ALIN_KUULA_X + 19+38, ALIN_KUULA_Y - 3*VALI)  
]   
